# Generated by Django 5.0.7 on 2024-08-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvancedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                ("productId", models.CharField(blank=True, max_length=255, null=True)),
                ("date_to_complete", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BoostedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                ("productId", models.CharField(blank=True, max_length=255, null=True)),
                ("date_to_complete", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PremiumHooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                ("productId", models.CharField(blank=True, max_length=255, null=True)),
                ("date_to_complete", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PremiumPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                ("productId", models.CharField(blank=True, max_length=255, null=True)),
                ("date_to_complete", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WildFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                ("productId", models.CharField(blank=True, max_length=255, null=True)),
                ("date_to_complete", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
