# Generated by Django 5.0.7 on 2024-07-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_advancedfilter_date_to_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advancedfilter",
            old_name="date_to_completed",
            new_name="date_to_complete",
        ),
        migrations.RenameField(
            model_name="boostedprofile",
            old_name="date_to_completed",
            new_name="date_to_complete",
        ),
        migrations.RenameField(
            model_name="premium",
            old_name="date_to_completed",
            new_name="date_to_complete",
        ),
        migrations.RemoveField(
            model_name="premiumhooked",
            name="date_to_completed",
        ),
        migrations.RemoveField(
            model_name="wildfeature",
            name="date_to_completed",
        ),
        migrations.AddField(
            model_name="premiumhooked",
            name="date_to_complete",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wildfeature",
            name="date_to_complete",
            field=models.DateField(blank=True, null=True),
        ),
    ]
