# Generated by Django 5.0.7 on 2024-07-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0007_rename_date_to_completed_advancedfilter_date_to_complete_and_more",
        ),
        ("users", "0005_user_coin_user_rose_user_teddy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Premium",
            new_name="PremiumPlus",
        ),
    ]
