# Generated by Django 5.0.7 on 2024-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_rename_premium_premiumplus"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedfilter",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="boostedprofile",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="premiumhooked",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="premiumplus",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wildfeature",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
