# Generated by Django 5.0.7 on 2024-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_advancedfilter_productid_boostedprofile_productid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedfilter",
            name="productId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="boostedprofile",
            name="productId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="premiumhooked",
            name="productId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplus",
            name="productId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wildfeature",
            name="productId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
