# Generated by Django 5.0.6 on 2024-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_sexual_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
