# Generated by Django 5.0.7 on 2024-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_emailactivated"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradvancedfilter",
            name="country",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="useradvancedfilter",
            name="state",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
