# Generated by Django 5.0.7 on 2024-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_useradvancedfilter_country_useradvancedfilter_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="readyForFamily",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useradvancedfilter",
            name="readyForFamily",
            field=models.TextField(blank=True, null=True),
        ),
    ]
