# Generated by Django 5.0.7 on 2024-08-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_readyforfamily_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useremailactivationcode",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
