# Generated by Django 5.0.7 on 2024-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_isonline"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coin",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="rose",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="teddy",
            field=models.IntegerField(default=0),
        ),
    ]
