# Generated by Django 5.0.7 on 2024-07-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_rename_premium_premiumplus"),
        ("users", "0005_user_coin_user_rose_user_teddy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="premium",
        ),
        migrations.AddField(
            model_name="user",
            name="premiumPlus",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premium",
                to="payments.premiumplus",
            ),
        ),
    ]
