# Generated by Django 5.0.6 on 2024-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(blank=True, null=True),
        ),
    ]
