# Generated by Django 5.0.7 on 2024-08-31 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_useremailactivationcode_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useremailactivationcode",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
