# Generated by Django 5.0.6 on 2024-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
