# Generated by Django 5.0.6 on 2024-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
