# Generated by Django 5.0.7 on 2024-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_countryoforigin_user_stateoforigin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="countryOfOrigin",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="stateOfOrigin",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useradvancedfilter",
            name="countryOfOrigin",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useradvancedfilter",
            name="stateOfOrigin",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
    ]
