# Generated by Django 5.0.7 on 2024-09-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_countryoforigin_alter_user_stateoforigin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="genotype",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="useradvancedfilter",
            name="genotype",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
