# Generated by Django 5.0.7 on 2024-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_genotype_useradvancedfilter_genotype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userCurrentLocation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
