# Generated by Django 5.0.6 on 2024-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_educationlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationshipGoal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
