# Generated by Django 5.0.6 on 2024-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_relationshipgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starSign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
