# Generated by Django 5.0.6 on 2024-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_starsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
