# Generated by Django 5.0.7 on 2024-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_usercurrentlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additionalCountries",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
