# Generated by Django 5.0.6 on 2024-07-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pet',
            new_name='pets',
        ),
    ]
