# Generated by Django 5.0.6 on 2024-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_profile_image_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
