# Generated by Django 5.0.6 on 2024-07-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_premiumhooked'),
        ('users', '0020_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premiumHooked',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='payments.premiumhooked'),
        ),
    ]
