# Generated by Django 5.0.6 on 2024-07-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wildfeature'),
        ('users', '0021_user_premiumhooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wildFeature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='payments.wildfeature'),
        ),
    ]
