# Generated by Django 5.0.6 on 2024-07-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_advancedfilter_parentsub'),
        ('users', '0022_user_wildfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advancedFilter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='payments.advancedfilter'),
        ),
    ]
