# Generated by Django 5.0.6 on 2024-07-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_boostedprofile_delete_parentsub'),
        ('users', '0023_user_advancedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boostedProfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='payments.boostedprofile'),
        ),
    ]
