# Generated by Django 5.0.6 on 2024-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_boostedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
