# Generated by Django 5.0.6 on 2024-07-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introvert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
