# Generated by Django 5.0.6 on 2024-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_introvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
