"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import firebase_admin
from firebase_admin import credentials
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&dg4n133@nlmkuxv(no538xe^$j109t9fvf9r*+cq2-542annj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "channels",


    "rest_framework",
    'django_celery_beat',
    'django_celery_results',
    "corsheaders",
    "rest_framework.authtoken",
    "storages",
    "django_seed",

    "users",
    "likes",
    "payments",
    "blocks",
    "reports",
    "chats",
    "deviceTokens",
    "notifications",
    "gifts",
    "likedPhotos",
    "hiddenProfiles",
    "savedUsers",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
# 'default1': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': "defaultdb", 
#     'USER': "doadmin",
#     'PASSWORD':"AVNS_v4SUZjBUoy-Xtl2OmEC",
#     'HOST':"db-postgresql-nyc3-15152-do-user-16518620-0.m.db.ondigitalocean.com", 
#     'PORT': "25060",
# },
'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': "d6fus9ik5abkkh", 
    'USER': "u7ft1fiaemli6b",
    'PASSWORD':"p0cf70194fac318d827dba04c3aa8480ac84325a01a832604a2d97e009cd584a9",
    'HOST':"c8m0261h0c7idk.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com", 
    'PORT': "5432",
},
 'default1': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "users.User"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],

    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}


CORS_ALLOW_ALL_ORIGINS = True
STRIPE_KEY = "sk_test_51MUgGhI5f8kSgDtfLUrAKVfw9kiUvUdRLGtud5gVpc5JZWar4lj7W6wDap0MP7YCaw52DLU4Nc87p72Wmt15CYOR00rgrNrz0j"


# AWS CONFIGURATIONS
AWS_ACCESS_KEY_ID = "AKIAQXZDR553VZ447CO4"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_ACL = None
AWS_STORAGE_BUCKET_NAME = "hookedapp1"
AWS_S3_CUSTOM_DOMAIN = "%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_LOCATION = "static"


if True:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": ['rediss://default:AVNS_Fu7c4zrbriYymm_G1yb@db-redis-nyc3-28044-do-user-16518620-0.e.db.ondigitalocean.com:25061'],
            },
        },
    }
    





# STATICFILES_STORAGE = os.path.join(BASE_DIR, 'static')
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
DEFAULT_FROM_EMAIL = "Hooked <support@jobaffairs.co>"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"


GENDERS = [
  "Male",
  "Female",
  "Non-binary",
  "I'd rather not say"
]

LOOKINGFOR = ['Men', 'Women',"Both" ]



cred = credentials.Certificate(BASE_DIR.joinpath("hooked-1c8c0-firebase-adminsdk-rcfsb-c516e375e9.json"))
firebase_admin.initialize_app(cred)


EMAIL_HOST = "smtp.mailgun.org"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = "Onhooked<support@onhooked.com>"
EMAIL_HOST_USER = "support@onhooked.com"
EMAIL_HOST_PASSWORD ="gODFATHERTINZ1@"
# USE_TZ = False