# Generated by Django 5.0.7 on 2024-09-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HideProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_hidden", models.DateTimeField(auto_now_add=True)),
                (
                    "hidden_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_i_hid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_hidden_from_i",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
