# Generated by Django 5.0.7 on 2024-08-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0003_alter_like_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="likedImage",
            field=models.TextField(blank=True, null=True),
        ),
    ]
