# Generated by Django 5.0.7 on 2024-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0005_remove_like_likedimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-id"]},
        ),
    ]
