# Generated by Django 5.0.7 on 2024-09-15 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savedUsers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveduser",
            name="date_saved",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
