# Generated by Django 5.0.7 on 2024-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="message_file",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_message_files/"
            ),
        ),
    ]
