# Generated by Django 5.0.7 on 2024-08-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notified_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-id"]},
        ),
    ]
